language: node_js
node_js:
  - "iojs"
  - "6"
before_script:
  - npm install grunt-cli -g
deploy:
  provider: releases
  api_key: ac1599248d3cdf36f6cc576ab970d6dfcd98db47
  file:
    - "app/js/app.js"
    - "app/css/site.css"
  skip_cleanup: true
  on:
    tags: true